name: Terraform

on:
  push:
    branches: [ master ]
  pull_request:

env:
  TF_WORKING_DIR: ./gke

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # for WIF

    steps:
      # 1. Get your code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Install Terraform and TFLint
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
      
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.50.3

      # 3. Init TFLint
      - name: Init TFLint
        run: tflint --init
        working-directory: ${{ env.TF_WORKING_DIR }}
        continue-on-error: true

      # 4. Run linters and security checks
      - name: Run TFLint
        run: tflint --format compact
        working-directory: ${{ env.TF_WORKING_DIR }}
     

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ${{ env.TF_WORKING_DIR }}
          soft_fail: true
      
      - name: Terraform Fmt
        run: terraform fmt -check
        working-directory: ${{ env.TF_WORKING_DIR }}

      # 5. Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5. Run Terraform commands
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve -input=false
